#!/bin/bash

#var color
RED='\033[0;31m'
BLUE='\033[0;34m'
LBLUE='\033[1;34m'
LGREEN='\033[1;32m'
LGREY='\003[0;37'
BLACK='\033[0;30'
NC='\033[0m'

#var folder
RBENV=/home/doyoque/.rbenv

#prerequisites for cocos2dx
echo -e "${RED}installing prerequisites${NC} for ${LBLUE}cocos2dx${NC}\n"
sudo apt-get install -y g++ \
cmake libgdk-pixbuf2.0-dev \
python-pip libx11-dev libxmu-dev \
libglu1-mesa-dev libgl2ps-dev libxi-dev \
libzip-dev libpng-dev libcurl4-gnutls-dev \
libfontconfig1-dev libsqlite3-dev libglew-dev \
libssl-dev libgtk-3-dev libglfw3 libglfw3-dev xorg-dev

#prerequisites for ruby environment
echo -e "${RED}installing prerequisites${NC} for ${RED}ruby environment${NC}\n"
sudo apt-get install -y git-core curl zlib1g-dev build-essential libssl-dev \
libreadline-dev libyaml-dev sqlite3 libxml2-dev libxslt1-dev \
libcurl4-openssl-dev libffi-dev

#installing lua and java environment
echo -e "${RED}installing${NC} ${LBLUE}lua${NC} and ${LBLUE}java environment${NC}\n"
sudo apt-get install -y lua5.2 \
default-jre default-jdk

#installing apache2, php, mysql
sudo apt-get install -y apache2 \
mysql-server php7.1 libapache2-mod-php7.1 php7.1-common php7.1-mbstring \
php7.1-xmlrpc php7.1-soap php7.1-gd php7.1-xml php7.1-intl php7.1-mysql \
php7.1-cli php7.1-mcrypt php7.1-zip php7.1-curl

#git clone ruby environment
echo -e "${BLACK}git clone rbenv and ruby-build${NC}\n"
if [ -d $RBENV ]; then
  echo "export PATH='$HOME/.rbenv/bin:$PATH'" >> ~/.bashrc
  echo "eval '$(rbenv init -)'" >> ~/.bashrc
  exec $SHELL
  echo -e "\n"
else
  git clone https://github.com/rbenv/rbenv.git ~/.rbenv
fi

if [ -d $RBENV ]; then
  echo "export PATH='$HOME/.rbenv/plugins/ruby-build/bin:$PATH'" >> ~/.bashrc
  exec $SHELL
else
  git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
fi

#run rbenv
echo -e "${RED}run rbenv${NC}\n"
rbenv install 2.4.0
rbenv global 2.4.0
ruby -v
#gem install bundler
#gem install rails
#gem install tmuxinator

#update, upgrade, and autoremove
echo -e "${LGREEN}do update, upgrade, and autoremove${NC}\n"
sudo apt-get update && sudo apt-get upgrade && sudo apt-get autoremove -y

